/**
 * NOTE: This data is not strictly necessary for the assignment, 
 * but was generated by ChatGPT and included because it will **likely** be helpful.
 * Feel free to modify, ignore or expand it as needed.
 */

const Genres = {
    ACTION: "Action",
    ADVENTURE: "Adventure",
    RPG: "Role-Play",
    FPS: "First-Person Shooter",
    STRATEGY: "Strategy",
    SPORTS: "Sports",
    HORROR: "Horror",
    SIMULATION: "Simulation",
    PUZZLE: "Puzzle",
    RACING: "Racing"
};

const VideoGames = [
    { id: 0, title: "The Legend of Zelda: Breath of the Wild", description: "An open-world action-adventure game set in Hyrule.", developer: "Nintendo", releaseYear: 2017, genre: Genres.ADVENTURE, averageRating: 9.8, numberOfReviews: 12000, released: true, image: "/images/gameImages/LOZBreathOfTheWild.jpg" },
    { id: 1, title: "The Witcher 3: Wild Hunt", description: "A sprawling RPG filled with monsters, magic, and rich storytelling.", developer: "CD Projekt Red", releaseYear: 2015, genre: Genres.RPG, averageRating: 9.7, numberOfReviews: 15000, released: true, image: "/images/gameImages/TheWitcher3WildHunt.jpg" },
    { id: 2, title: "Half-Life 2", description: "A groundbreaking first-person shooter with physics-based gameplay.", developer: "Valve", releaseYear: 2004, genre: Genres.FPS, averageRating: 9.6, numberOfReviews: 10000, released: true, image: "/images/gameImages/HalfLife2.jpg" },
    { id: 3, title: "Dark Souls III", description: "A brutally challenging RPG with rich lore and deep combat.", developer: "FromSoftware", releaseYear: 2016, genre: Genres.RPG, averageRating: 9.4, numberOfReviews: 8500, released: true, image: "/images/gameImages/DarkSouls3.jpg" },
    { id: 4, title: "Minecraft", description: "A sandbox game where you can build and explore infinite worlds.", developer: "Mojang", releaseYear: 2011, genre: Genres.SIMULATION, averageRating: 9.5, numberOfReviews: 20000, released: true, image: "/images/gameImages/Minecraft.avif" },
    { id: 5, title: "Celeste", description: "A heartfelt platformer about climbing a mountain while overcoming personal struggles.", developer: "Maddy Makes Games", releaseYear: 2018, genre: Genres.ADVENTURE, averageRating: 9.5, numberOfReviews: 800, released: true, image: "/images/gameImages/Celeste.avif" },
    { id: 6, title: "Hollow Knight", description: "A hand-drawn Metroidvania with deep exploration and tight combat.", developer: "Team Cherry", releaseYear: 2017, genre: Genres.ADVENTURE, averageRating: 9.5, numberOfReviews: 7500, released: true, image: "/images/gameImages/HollowKnight.jpeg" },
    { id: 7, title: "Katana ZERO", description: "A stylish neo-noir action-platformer with fast-paced combat.", developer: "Askiisoft", releaseYear: 2019, genre: Genres.ACTION, averageRating: 9.0, numberOfReviews: 600, released: true, image: "/images/gameImages/KatanaZero.jpg" },
    { id: 8, title: "Outer Wilds", description: "A mystery exploration game set in a solar system trapped in a time loop.", developer: "Mobius Digital", releaseYear: 2019, genre: Genres.ADVENTURE, averageRating: 9.3, numberOfReviews: 900, released: true, image: "/images/gameImages/OuterWilds.avif" },
    { id: 9, title: "Disco Elysium", description: "A narrative-driven RPG where you play as a detective with unique skill-based dialogue.", developer: "ZA/UM", releaseYear: 2019, genre: Genres.RPG, averageRating: 9.6, numberOfReviews: 950, released: true, image: "/images/gameImages/DiscoElysium.jpg" },
    { id: 10, title: "Starfield", description: "A space exploration RPG from the creators of Fallout and Skyrim.", developer: "Bethesda Game Studios", releaseYear: 2023, genre: Genres.RPG, averageRating: null, numberOfReviews: 0, released: false, image: "/images/gameImages/Starfield.jpg" },
    { id: 11, title: "Metroid Prime 4", description: "The next installment in the Metroid Prime series.", developer: "Nintendo", releaseYear: 2025, genre: Genres.ACTION, averageRating: null, numberOfReviews: 0, released: false, image: "/images/gameImages/MetroidPrime4.avif" },
    { id: 12, title: "Hollow Knight: Silksong", description: "A sequel to the acclaimed indie Metroidvania, Hollow Knight.", developer: "Team Cherry", releaseYear: 2024, genre: Genres.ADVENTURE, averageRating: null, numberOfReviews: 0, released: false, image: "/images/gameImages/HNSilksong.jpg" },
    { id: 13, title: "Grand Theft Auto VI", description: "The next major entry in the Grand Theft Auto series.", developer: "Rockstar Games", releaseYear: 2025, genre: Genres.ACTION, averageRating: null, numberOfReviews: 0, released: false, image: "/images/gameImages/GTA6.jpg" },
    { id: 14, title: "Red Dead Redemption 2", description: "An open-world western action-adventure game.", developer: "Rockstar Games", releaseYear: 2018, genre: Genres.ACTION, averageRating: 9.7, numberOfReviews: 14000, released: true, image: "/images/gameImages/RDR2.jpg" },
    { id: 15, title: "DOOM Eternal", description: "A fast-paced first-person shooter that rewards aggressive gameplay.", developer: "id Software", releaseYear: 2020, genre: Genres.FPS, averageRating: 9.2, numberOfReviews: 5000, released: true, image: "/images/gameImages/DoomEternal.jpeg"},
    { id: 16, title: "Sid Meier's Civilization VI", description: "A turn-based strategy game where you build and expand an empire.", developer: "Firaxis Games", releaseYear: 2016, genre: Genres.STRATEGY, averageRating: 9.0, numberOfReviews: 4000, released: true, image: "/images/gameImages/SMC6.jpg" },
    { id: 17, title: "Bloodborne", description: "A gothic horror action RPG with intense combat and a rich world.", developer: "FromSoftware", releaseYear: 2015, genre: Genres.RPG, averageRating: 9.6, numberOfReviews: 9000, released: true, image: "/images/gameImages/Bloodborne.avif" },
    { id: 18, title: "Super Mario Odyssey", description: "A globe-trotting 3D platformer featuring Mario and his hat companion, Cappy.", developer: "Nintendo", releaseYear: 2017, genre: Genres.ADVENTURE, averageRating: 9.7, numberOfReviews: 11000, released: true, image: "/images/gameImages/SuperMarioOdyssey.jpg" },
    { id: 19, title: "Cyberpunk 2077", description: "A futuristic RPG set in a cyberpunk city with branching stories.", developer: "CD Projekt Red", releaseYear: 2020, genre: Genres.RPG, averageRating: 8.9, numberOfReviews: 6000, released: true, image: "/images/gameImages/Cyberpunk2077.jpeg" },
    { id: 20, title: "God of War (2018)", description: "A third-person action-adventure featuring Kratos and his son, Atreus.", developer: "Santa Monica Studio", releaseYear: 2018, genre: Genres.ACTION, averageRating: 9.8, numberOfReviews: 12000, released: true, image: "/images/gameImages/GodOfWar.jpeg" },
    { id: 21, title: "The Elder Scrolls V: Skyrim", description: "A vast open-world RPG filled with quests, dragons, and adventure.", developer: "Bethesda Game Studios", releaseYear: 2011, genre: Genres.RPG, averageRating: 9.6, numberOfReviews: 16000, released: true, image: "/images/gameImages/Skyrim.avif" },
    { id: 22, title: "Persona 5 Royal", description: "A stylish turn-based RPG about high school students fighting injustice.", developer: "Atlus", releaseYear: 2020, genre: Genres.RPG, averageRating: 9.7, numberOfReviews: 8000, released: true, image: "/images/gameImages/Persona5Royal.jpg" },
    { id: 23, title: "FIFA 23", description: "The latest iteration of the FIFA soccer series.", developer: "EA Sports", releaseYear: 2022, genre: Genres.SPORTS, averageRating: 8.1, numberOfReviews: 3000, released: true, image: "/images/gameImages/FIFA23.avif" },
    { id: 24, title: "Forza Horizon 5", description: "An open-world racing game set in Mexico.", developer: "Playground Games", releaseYear: 2021, genre: Genres.RACING, averageRating: 9.4, numberOfReviews: 5000, released: true, image: "/images/gameImages/ForzaHorizon5.jpg" },
    { id: 25, title: "Resident Evil 4 (Remake)", description: "A modern reimagining of the classic survival horror game.", developer: "Capcom", releaseYear: 2023, genre: Genres.HORROR, averageRating: 9.5, numberOfReviews: 7000, released: true, image: "/images/gameImages/RE4.jpg" },
    { id: 26, title: "The Forgotten City", description: "A time-loop mystery adventure set in an ancient Roman city.", developer: "Modern Storyteller", releaseYear: 2021, genre: Genres.ADVENTURE, averageRating: 9.0, numberOfReviews: 700, released: true, image: "/images/gameImages/TheForgottenCity.jpg" },
    { id: 27, title: "Return of the Obra Dinn", description: "A detective puzzle game where you solve the fate of a lost ship's crew.", developer: "Lucas Pope", releaseYear: 2018, genre: Genres.PUZZLE, averageRating: 9.2, numberOfReviews: 500, released: true, image: "/images/gameImages/ReturnOfTheObraDinn.jpg" },
    { id: 28, title: "Slay the Spire", description: "A deck-building rogue-like where you fight through floors of enemies using strategic card combos.", developer: "MegaCrit", releaseYear: 2019, genre: Genres.STRATEGY, averageRating: 9.1, numberOfReviews: 850, released: true, image: "/images/gameImages/SlayTheSpire.avif" },
    { id: 29, title: "Inscryption", description: "A unique blend of deck-building, escape room puzzles, and psychological horror.", developer: "Daniel Mullins Games", releaseYear: 2021, genre: Genres.PUZZLE, averageRating: 9.3, numberOfReviews: 950, released: true, image: "/images/gameImages/Inscryption.jpg" },
    { id: 30, title: "Loop Hero", description: "A rogue-like where you shape the world around a looping hero's journey.", developer: "Four Quarters", releaseYear: 2021, genre: Genres.STRATEGY, averageRating: 9.0, numberOfReviews: 700, released: true, image: "/images/gameImages/LoopHero.jpg" },
    { id: 31, title: "A Short Hike", description: "A relaxing exploration game where you hike up a mountain at your own pace.", developer: "Adam Robinson-Yu", releaseYear: 2019, genre: Genres.ADVENTURE, averageRating: 9.4, numberOfReviews: 500, released: true, image: "/images/gameImages/AShortHike.avif" },
    { id: 32, title: "Into the Breach", description: "A turn-based strategy game where you control mechs defending against alien threats.", developer: "Subset Games", releaseYear: 2018, genre: Genres.STRATEGY, averageRating: 9.3, numberOfReviews: 650, released: true, image: "/images/gameImages/IntoTheBreach.jpg" },
    { id: 33, title: "Bug Fables: The Everlasting Sapling", description: "A charming RPG inspired by classic Paper Mario games.", developer: "Moonsprout Games", releaseYear: 2019, genre: Genres.RPG, averageRating: 9.0, numberOfReviews: 750, released: true, image: "/images/gameImages/BFEverlasting.jpeg" },
    { id: 34, title: "Eastward", description: "A pixel-art adventure RPG featuring a world filled with puzzles and charm.", developer: "Pixpil", releaseYear: 2021, genre: Genres.RPG, averageRating: 9.1, numberOfReviews: 600, released: true, image: "/images/gameImages/Eastward.jpeg" },
    { id: 35, title: "Borderlands 4", description: "Four Vault Hunters battle across the planet Kairos using wild weapons, grappling hooks, and open-world traversal.", developer: "2K Games", releaseYear: 2025, genre: Genres.RPG, released: false, image: "/images/gameImages/Borderlands4.jpg"},
    { id: 36, title: "Silent Hill f", description: "Set in 1960s Japan, a student faces horrifying creatures as the cursed town of Ebisugaoka unravels.", developer: "Konami Digital Entertainment", releaseYear: 2025, genre: Genres.HORROR, released: false, image: "/images/gameImages/SilentHillf.avif"},
    { id: 37, title: "LEGO Batman: Legacy of the Dark Knight", description: "Explore Gotham as LEGO Batman across eras, fighting villains and building through classic stories.", developer: "Warner Bros. Games", releaseYear: 2026, genre: Genres.ADVENTURE, released: false, image: "/images/gameImages/LEGOBatman.jpg"},
    { id: 38, title: "Warhammer 40,000: Boltgun II", description: "Blast through chaos as a Space Marine or Sister of Battle in a brutal, fast-paced Warhammer campaign.", developer: "Big Fan Games (Devolver Digital)", releaseYear: 2026, genre: Genres.FPS, released: false, image: "/images/gameImages/Warhammer40kBoltgun2.jpg"},
];

module.exports = { Genres, VideoGames };
